version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm config set ${NPM_RC}
      - npm install -g typescript
      - npm install
  pre_build:
    commands:
      - echo no command for pre build
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
  name: molink-viewer-$(date +%Y-%m-%d)
